### ISSUE TITLE
-32768 isn't a valid value in Jack

### ISSUE THREAD

**Issue by QuesterZen** [idelvall/nand-mines#1]
Could you please add a test for 0000 0000 0000 0001 and ensure it is coded as ~32767 instead of -32768 since -32768 is not a valid input value in Jack.
The problem is that -32768 generates the VM code:
```
push 32768
neg 
```
which in turn produces the assembly command
```
@32768
```
which fails because the binary for an @ command is 0 followed by a 15 bit value and 32768 uses the 16th bit.

Eg.a quick fix would be to insert at line 163: 
```
if (value == -32768) 
    generateCode.value = generateCode.value + "\tdo Memory.poke(memAddress+" + row*32 + ", ~32767);\n"; 
else
    generateCode.value = generateCode.value + GenerateCodeLine(i, value);
```
and delete line 164. Or the same test could be moved to the GenerateCodeLine function.

Note that this is a bug in the original version of the Sokoban bitmap editor also.

**Comment by idelvall** [comment]
Hi, this is arguably a bug in the Sokoban bitmap editor. 
It's true, that for making it work (currently) you have to do the hack you mention but, (IMO) it is responsability of the Jack compiler to handle it, since **from the perspective of the Jack developer** `32768` is indeed a valid integer literal.  

Don't you think?

**Comment by QuesterZen** [comment]
I agree that it **should** be a valid integer literal, but in the Jack language specification ('The Elements of Computing Systems', Chapter 10 - Compiler I: Syntax Analysis, on page 208) an integerConstant is defined as "A decimal number in the range 0 .. 32767". So it is not an issue of a bug in the supplied compiler, but actually of the language specification itself.
(Note that the supplied Jack compiler does enforce this restriction, but it completely fails to enforce the correct description of a StringConstant!)

**Comment by idelvall** [comment]
I was unaware of this restriction imposed by the specs. I that case, nothing more to say.
Thanks!
